name: Release

on:
  push:
    branches:
      - main
    paths:
      - 'curated/**'
      - ".github/workflows/release.yaml"
      - "yarn.lock"
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'yarn'

      - name: Auth with npm registry
        run: |
          echo 'npmScopes:
                  ei-tech:
                    npmAlwaysAuth: true
                    npmRegistryServer: "https://registry.npmjs.org"
                    npmAuthToken: ${{ secrets.NPM_TOKEN }}' >> ~/.yarnrc.yml

      - name: Install Dependencies
        run: yarn --immutable

      - name: Build Packages
        run: yarn build

      - name: Run Tests
        run: yarn test


      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          version: yarn version
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
